/*
  # [Operation Name]
  Add keyword fields to reference_folders table

  ## Query Description:
  This operation adds `manual_keywords` and `auto_keywords` columns to the `reference_folders` table. These fields are essential for the AI's reference matching logic. This is a non-destructive change and will not affect existing data.

  ## Metadata:
  - Schema-Category: "Structural"
  - Impact-Level: "Low"
  - Requires-Backup: false
  - Reversible: true

  ## Structure Details:
  - Table: `public.reference_folders`
  - Columns Added: `manual_keywords` (text[]), `auto_keywords` (text[])

  ## Security Implications:
  - RLS Status: Unchanged
  - Policy Changes: No
  - Auth Requirements: None

  ## Performance Impact:
  - Indexes: None added
  - Triggers: None added
  - Estimated Impact: Negligible. Existing queries will not be affected.
*/

ALTER TABLE public.reference_folders
ADD COLUMN IF NOT EXISTS manual_keywords text[] DEFAULT '{}'::text[],
ADD COLUMN IF NOT EXISTS auto_keywords text[] DEFAULT '{}'::text[];

COMMENT ON COLUMN public.reference_folders.manual_keywords IS 'Keywords manually added by the user to fine-tune reference matching.';
COMMENT ON COLUMN public.reference_folders.auto_keywords IS 'Keywords automatically generated by AI analysis of the folder''s images.';
